language: python

python:
  - "3.6.5"

addons:
  firefox: "latest"
  # sauce_connect: true

env:
  global:
    BrowserStack credentials:
      - secure: "mwxbzWDEcgcs+N9+8eBzs1G5lHG8A5QhB6He2s3Re7UL/E4qPbXFmnRkP8iQd00efVdiGu1R9jKMVMTspG5JIq4AtWggCtOMQ8DDVtaHRgK7iLUFr1RdHzjqjR+ZX/8+tjvzCiGl+tqVTc1BpIje7HPEMMNWtm6oaeUEOs31RiY/XTIcoX/F75AMGpn8tQISrz6Y/5JH4u5ClDI6JlnFp/7lxm/IDUl2nO1PQhVrDzsxY8zCgcPF09dEQOF7J94D99ytYEiSGvSNWitptZSvLOJl+mlR6DGLhkpB1f5gSNtl4FfU4oCe+HziO8MAh1lOIzzS7+hVXgotICf0zSYkVGHWzx4sILT8DMAV3/14CPVTVx2Hw4T/mCH5n8O9jkkMlE/n92WF1f0Xe2ZZRbgMgPUCIcoJjmw44jj+kVy3w08xhoULcPhsJV+GfmzuBuPZCiGsPbHNLSzGdbFMqhtNeVEHTjaRoLwqOugOAAIBg2W5WUJR+me5JZEY3zGhu5sbGeUjuezXqSScjYIPA0W2SS6E1t7kobqBch8QnpZ0M2dBluIL0O7uYp7DQdXWYoLMDbXe5kRzDF+kj6EVvyS9TkpN7szznr5PmNQzaxvnM/+gAc8SVM/R/cKA5X0jh9y2zGKtySaBet1qqAaWq4KPegWydYeKaWz+TaE7wVlwwSQ="
      - secure: "WVKXmz0jCYr8OzUsSv/dxom5uSL1J7mToEnyUbcBGSGepkO1KzoazDI17vcleTGWD46LhGgq650XWEaB468r+qsWgYWh7f+fgxpcrKkv1tcCJJ7sRlr5Cd1c0qAEbq7emE0d94U9H+JDOf6krQwr+5PhlwPlrB1bzX5/62uuFjIVnz6gHQhYsIZ83HlvvlD1Oo2TSNYWZrRU2gtEvnVQHR/1aV+8yd9Bs9KsZ74+SN8vi7lZ0Z/EQ9OZm2YkYKxfwvZkkobz2LC6ICENfeUlXueazU8Of0vKy+oeamooRB6UedpOyaFa/pg6kgmLzO9V0PzLGKa3ngYtDd9jcdaN9p9rEoK+NONABrPBo4q6ZIDu1XxJxNZHlQVe5TUi3ybd1kayJifwV7KvgwnaKwjcdEYUaUsOW99hZ6BsqdSBqfhJd+ajOo7QeAQxC+lUMkpYZdZzKrb7e9RLU5kyVQWYIGbWgaZjJjloN4hIc9aoovXdhBKWVzSlq0yweQ+xfXywWRuzWT4UPczfXPRv+WDYkbxIaLZRp82gEg3JkXkvWs1QKAIC83akO4+1ls4tdqaOCtY197ww6lEUPAICmnFnZphrLRwz3bQAJFofRRu0qRHXF8E7xBd+AmGZAOl0Phh2ebkYBnf4Pn3RCpphoPAtI6sotW/O97/6Wgnz37rkGp4="
  # SauceLabs credentials:
  # - secure: "joQWAKGrqlg5Ua33G8UHNB7LxgSZHFnZqTev11BLSNlZhIJxFrl7x0CyxvxRUq6s+Fppbrqz9qu0RTqqRWtqUCfKxLiEprSH2RcK5OvPhX0DsWj6mOsJz8WM2DItB6zDmTTRojgTCehw+mXrVhkW+tVrSdLqs3a/ef7YOool5tsae2lQs2wuoIg3k8nTQP9RE2YXBAQRbLPA/nEOHWaERsefb3gZwONNu6KHDnhaUXHXjnbo2eMBS8H8H7fmMrU178Pz5zno8d0Eg26370DEFdOGlX/YX4aiqZzS8AhG9uNY0yG+8n8uY6rNJmwbpxXC2AuPHvlTsKd6kZXn+lEHFkMYG0gGOjLIUU80SWadOYkwzMrM1bhcSNMTWk3C0aV3wHXVaoSlGX2pfgXOXcrPbNNbMz2I+bgvXhXBbiGE7Zc810Nr18CIcRQ5mbCjxBJk7cUReRIkq3PGIzOjYRjbT0nhkVWCfNoDkOZHvjXNIWJIi7d+w78d1CJa7/z3HyFwS5wpNrjxkdE2UPHL1y1RrBLl25nxy9KUWOImfeYbym12tebVX4TPH3WrLkCGFT3OEt/B2f2HEF614kA2JNR3cB5jvWT94SJybEAtk6RFPf9qjrbAfBg5SeqzZ17/vJmmZxDcHzuze1+tLFZPXNNHBwyqt4TI9MxdYZb+L328qjY="
  # - secure: "imY7FAhE1vhXy74SjrwNxnfTvr6jwMS4O+wURCNNdjP2it+klHqguBKSIAt/ZoFGhN5sx4faqKu0HGf3ya/TA87Suh1FJFX9+IgpU1c3mVtvOCJKVhITNM8Oyncza1FO9rOinUXKHHAA5a4sCdUFFx+rDGGGoUozr2lacGq3TuHjyji5+phLxGJ/EExFoV4kE7u7nTSCAVJKIvF4ERzJvij9fWAs//vjnHNhb5uGIPAy8JNRgDGMX/YnyexaVN91pNFsoRIkVeyxYPQNsPT2lLf0vRuI/6Ce5i2uOJpfxn5HMpyeHlIb6qRM6pR6FrcfPxxyY5FK4sTbYZjpKOQAc5y1K3PdukaGYkWIKAZjwzzD8L9mVZmOfafC/4nCWdhh9JAzSFUM6guHKyM8zFKdpUz9mZkY+v1AvnZCb3dj52KBJ+tK/rGo6o8HVt6isu6sN6PMdMWELWjdcSucwzxgvsgvUln1nbCx4e0/8u9v4zV9hcnbGBZX3gZO6vtosyeDrqeuaTCCRqWBgVXHHsWsTz+1UTvJkIFGZpszQDO2pyh5vQ6/WcLqkFl0JA8u5Ti1xRMRu+KJSIc4tT8D22f2tJnZPyyIwjZbctn27Bm2LFRFWGkY545A2GOtDG8RxEAgQyIkL+FsC9/ljN3Xpc/AaTMfqKe5qVZQusdzV7sb7kE="
matrix:
  - KARMA_BROWSERSTACK=1 COVERAGE=1 TEST_TARGET=test
  # - KARMA_SAUCE_LABS=1 TEST_TARGET=test-assets

matrix:
  fast_finish: true
  # allow_failures:
  #  - env: KARMA_SAUCE_LABS=1 TEST_TARGET=test-assets

before_install:
  - nvm install $(python -c "import json; print(json.loads(open('./assets/package.json').read())['engines']['node'])")

install:
  - make env
  - gem install coveralls-lcov

before_script:
  - mkdir coverage

script:
  - make test
  - make "$TEST_TARGET"

after_success:
  - "[[ -n $COVERAGE ]] && make coverage"
