language: python

python:
  - "3.6.5"

addons:
  firefox: "latest"


before_install:
  - nvm install $(python -c "import json; print(json.loads(open('./assets/package.json').read())['engines']['node'])")

install:
  - make env
  - gem install coveralls-lcov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - mkdir coverage

script:
  - wdfn-server/env/bin/coverage run --omit=wdfn-server/waterdata/tests/*.py,wdfn-server/env/* -m pytest wdfn-server/waterdata
  - cd assets && npm run test

after_success:
  - cd ../
  - find assets/coverage/ -mindepth 2 -iname '*.info' -exec cp -t coverage/ '{}' +
  - coveralls-lcov -v -n coverage/lcov.info > coverage/coverage.json
  - wdfn-server/env/bin/coveralls --merge=coverage/coverage.json

