language: python

python:
  - "3.6"

before_install:
  - nvm install $(python -c "import json; print(json.loads(open('./package.json').read())['engines']['node'])")

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - coverage run --omit=waterdata/tests/*.py,/home/travis/virtualenv/* -m unittest
  - npm run test

after_success:
  - coveralls
