language: python

python:
  - "3.6.5"

addons:
  firefox: "latest"
  # sauce_connect: true

env:
  global:
    # BrowserStack credentials:
    - secure: "NPGkqMSJ+zyemNRaCa2LDouedMAw2xXwoculORMvHeIL1+9HtT51VfFSEgI7NEHYEB3NSAfNgNKk47YQPqMeniiXbrmEOvQUNI2wE9isxtj4xEpc+7JjzsX7I/E8MST74lexXKIl4DZK0SJEGeR3D8WkdAx0C9oLzPE2bhKnShijyiMp4d4zzzernWq7rZEWITTS9lzi3Ex9rWYnyi148wX7rlHJgZfRCCGDvn+HvcJR+cLCT3mK2O6XGsH8HC9tEnec+x2WMIsPtyAm9vnpeR8t4MnO7xRHrPWA0YMhs1lV9jZASQxC4C1P40T6Ki1BEXbArMZEL1lSQ3IIyDEcstEaf6JHTdVD82/ZOiZfv0Lw6qNqnNnLA/q2wy6TTtU4UNeUkOiEDEMp3YJecTDs4NzB8mFpe1zzPK3TQlIszChdf3YzpORhInLqFlgRycsz0XYsG5UD60ZgC1CbdhQtkk2JYOoTqmhPY84QDsB5NahWT43lhgN3lM/Sou/U6wKA/7poqErrRZ826TCCB355pUQutPYeLHK9iY4AuMrYC/zcV46ybCaQEgmKa2TIsw+cedKyS+kT+1UW2SzLiA9XGP54+BojVUg904OZ69C8Tks/mYPmzkIJlDScldHcKyycbiF5mMvWA8aq4/fEJuDRbz+uJKRlFhWgKUPaon392XI="
    - secure: "qrTBKOaXyLt7F3HaB6040T749f0OViOiRcDItcRXVlZnMWpcPEapHxqWk/Eou1klK117NjilQ7+KZPNYPc+WdKmIlS6IehfII/eP9+vOC25y5Q9lwJcRTJF6U4VWmUrNi9DB9uXYOfuGcyabnP7xFiCWS1FB/1SbPovmwmjq66IEJx8/cJlbVjDcF60Y6u7bZcvG4vkP9UYvIKOLsbgjjYIavOzoOX+NDQ6koRfQA+ftqjU5A0th5jdlwDARdvqePgENlQJHv8KBRxQYO6QVs3+F4N2OrIGPSe5V4/kxhewzBepB3pobErHN+/LT+iTusxSJ+Bf/F0CLf9vGwz8jg5csdZlDkd7JkrSPm9ZP637Y5SBWdQhEPk/QbeWhhs7y4Xuo5On4hd0W7Fs0tdC0DXz0D2K+yKx2WlNmJDuV4gHAiXDy8Ek5o6pi3SPzKk/fY8eWJ3vV9O+FHuhoCWTPLSQ5SS8g/bI+9jyIGhDp1TeG/DVlPTJxD92UmhNHQ3F0x+n/ZEkqz9+tw4iXx6xVXqG/osMcOk6KY/TWYtWewq0wAoTHJhqzK8aUQjQSUYzs61RJq7DOn5ZrQu4K1TfOHXq1OMqaP/b5yDUiDgLX50GqHcTPKEDqOvbq4iLsGz0uiykQLPofab5W0ehwDB4kHmduH/yYbgyDtzDpnQEp6mk="
  # SauceLabs credentials:
  # - secure: "joQWAKGrqlg5Ua33G8UHNB7LxgSZHFnZqTev11BLSNlZhIJxFrl7x0CyxvxRUq6s+Fppbrqz9qu0RTqqRWtqUCfKxLiEprSH2RcK5OvPhX0DsWj6mOsJz8WM2DItB6zDmTTRojgTCehw+mXrVhkW+tVrSdLqs3a/ef7YOool5tsae2lQs2wuoIg3k8nTQP9RE2YXBAQRbLPA/nEOHWaERsefb3gZwONNu6KHDnhaUXHXjnbo2eMBS8H8H7fmMrU178Pz5zno8d0Eg26370DEFdOGlX/YX4aiqZzS8AhG9uNY0yG+8n8uY6rNJmwbpxXC2AuPHvlTsKd6kZXn+lEHFkMYG0gGOjLIUU80SWadOYkwzMrM1bhcSNMTWk3C0aV3wHXVaoSlGX2pfgXOXcrPbNNbMz2I+bgvXhXBbiGE7Zc810Nr18CIcRQ5mbCjxBJk7cUReRIkq3PGIzOjYRjbT0nhkVWCfNoDkOZHvjXNIWJIi7d+w78d1CJa7/z3HyFwS5wpNrjxkdE2UPHL1y1RrBLl25nxy9KUWOImfeYbym12tebVX4TPH3WrLkCGFT3OEt/B2f2HEF614kA2JNR3cB5jvWT94SJybEAtk6RFPf9qjrbAfBg5SeqzZ17/vJmmZxDcHzuze1+tLFZPXNNHBwyqt4TI9MxdYZb+L328qjY="
  # - secure: "imY7FAhE1vhXy74SjrwNxnfTvr6jwMS4O+wURCNNdjP2it+klHqguBKSIAt/ZoFGhN5sx4faqKu0HGf3ya/TA87Suh1FJFX9+IgpU1c3mVtvOCJKVhITNM8Oyncza1FO9rOinUXKHHAA5a4sCdUFFx+rDGGGoUozr2lacGq3TuHjyji5+phLxGJ/EExFoV4kE7u7nTSCAVJKIvF4ERzJvij9fWAs//vjnHNhb5uGIPAy8JNRgDGMX/YnyexaVN91pNFsoRIkVeyxYPQNsPT2lLf0vRuI/6Ce5i2uOJpfxn5HMpyeHlIb6qRM6pR6FrcfPxxyY5FK4sTbYZjpKOQAc5y1K3PdukaGYkWIKAZjwzzD8L9mVZmOfafC/4nCWdhh9JAzSFUM6guHKyM8zFKdpUz9mZkY+v1AvnZCb3dj52KBJ+tK/rGo6o8HVt6isu6sN6PMdMWELWjdcSucwzxgvsgvUln1nbCx4e0/8u9v4zV9hcnbGBZX3gZO6vtosyeDrqeuaTCCRqWBgVXHHsWsTz+1UTvJkIFGZpszQDO2pyh5vQ6/WcLqkFl0JA8u5Ti1xRMRu+KJSIc4tT8D22f2tJnZPyyIwjZbctn27Bm2LFRFWGkY545A2GOtDG8RxEAgQyIkL+FsC9/ljN3Xpc/AaTMfqKe5qVZQusdzV7sb7kE="
  matrix:
    - KARMA_BROWSERSTACK=1 COVERAGE=1 TEST_TARGET=test
    # - KARMA_SAUCE_LABS=1 TEST_TARGET=test-assets

matrix:
  fast_finish: true
  # allow_failures:
  #  - env: KARMA_SAUCE_LABS=1 TEST_TARGET=test-assets

before_install:
  - nvm install $(python -c "import json; print(json.loads(open('./assets/package.json').read())['engines']['node'])")

install:
  - make env
  - gem install coveralls-lcov

before_script:
  - mkdir coverage

script:
  - make "$TEST_TARGET"

after_success:
  - "[[ -n $COVERAGE ]] && make coverage"
