language: python

python:
  - "3.6"

addons:
  firefox: "latest"


before_install:
  - nvm install $(python -c "import json; print(json.loads(open('./package.json').read())['engines']['node'])")

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
  - npm install
  - gem install coveralls-lcov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - coverage run --omit=waterdata/tests/*.py,lookup_generation/tests/*.py,/home/travis/virtualenv/* -m pytest waterdata
  - npm run test

after_success:
  - find coverage/ -mindepth 2 -iname '*.info' -exec cp -t coverage/ '{}' +
  - coveralls-lcov -v -n coverage/lcov.info > coverage/coverage.json
  - coveralls --merge=coverage/coverage.json
