# This base config defines the production containers.

version: "3"

services:
  # Node-based static asset build tooling
  assets:
    build: ./assets
    image: wdfn_assets
    ports:
      - "9000:9000"
  # Node server-renderer
  graph_server:
    privileged: true
    build: ./graph-server
    image: wdfn_graph_server
    depends_on:
      - assets
    ports:
      - "2929:2929"
  # Python WSGI server
  # wdfn_server:
  #   build: ./wdfn-server
  #   image: wdfn_graph_server
  #   depends_on:
  #     - assets
  #   ports:
  #     - "5050:5050"
