# These overrides are useful for local development purposes and will be loaded
# by default when executing `docker-compose up`.
# Put custom config in local.env.

version: "3.7"

services:
  assets:
    command: npm run watch
    volumes:
      - ./assets:/assets
      - ./volumes/assets/node_modules:/assets/node_modules
  graph_server:
    volumes:
      - ./graph-server/src:/graph-server/src
      - ./assets/dist:/assets
      - ./volumes/graph-server/node_modules:/graph-server/node_modules
    command: npm run watch
