# These overrides are useful for local development purposes and will be loaded
# by default when executing `docker-compose up`.
# Put custom config in local.env.

version: "3"

services:
  assets:
    command: npm run watch
    volumes:
      - ./assets:/assets
      - ./volumes/assets/node_modules:/assets/node_modules
  graph_server:
    volumes:
      - ./graph-server/src:/graph-server/src
      - ./assets/dist:/assets
      - ./volumes/graph-server/node_modules:/graph-server/node_modules
    command: npm run watch
  # wdfn_server:
  #   volumes:
  #     - ./wdfn-server:/wdfn-server
  #   command: python run.py --host 0.0.0.0
  #   env_file:
  #     - local.env
